[package]
name = "simple-ecdh"
version = "0.1.0"
edition = "2024"

[dependencies]
md-5 = "0.10.6"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-traits = "0.2.19"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.7.0"
once_cell = "1.21.3"

[[bench]]
name = "bench"
harness = false
